# This is a basic workflow to help you get started with Actions

name: Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Ls Cuz I Do Not Understand The Docs
        run: ls
      
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
